version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Packaging app"

artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/install_deps.sh
  discard-paths: no
